import type { Metadata } from "next";
import "./globals.css";
import { RootClient } from "./rootClient";
import { NextAuthProvider } from "./_providers/nextauthProvider/NextAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: true,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <RootClient>{children}</RootClient>
        </NextAuthProvider>
      </body>
    </html>
  );
}
